version: "3"
services:
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
    restart: always
  mongodb:
    image: mongo:4.2.0
    restart: always
    container_name: mongo_db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DB: ${MONGODB_DB}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb_data:/data/db
      - ./init-db.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  mongodb_data:
