version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
